_wandb:
    value:
        cli_version: 0.25.1
        e:
            ju8fmglts2ur925f45wej9g7gpwr8jad:
                codePath: cbond_on\run\model_eval.py
                codePathLocal: cbond_on\run\model_eval.py
                cpu_count: 20
                cpu_count_logical: 20
                disk:
                    /:
                        total: "1023875739648"
                        used: "214716059648"
                email: 1094028578@qq.com
                executable: C:\Users\BaiYang\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 1015609bc843537f3c73cc1f74ef491ff75d133d
                    remote: git@10.1.30.16:JebGong/cbond_on.git
                host: gongweichen-pc
                memory:
                    total: "33726935040"
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\BaiYang\CBOND_ON\cbond_on\cbond_on\run\model_eval.py
                python: CPython 3.11.9
                root: C:\Users\BaiYang\CBOND_ON\cbond_on
                startedAt: "2026-04-07T06:39:33.128217Z"
                writerId: ju8fmglts2ur925f45wej9g7gpwr8jad
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 8
                - 53
            "2":
                - 1
                - 5
                - 8
                - 53
            "3":
                - 2
                - 14
                - 15
                - 62
            "4": 3.11.9
            "5": 0.25.1
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.1
            "13": windows-amd64
lgbm_params_max_depth:
    value: 12
lgbm_params_num_leaves:
    value: 63
lgbm_params_reg_alpha:
    value: 0.1
lgbm_params_reg_lambda:
    value: 0.1
