_wandb:
    value:
        cli_version: 0.25.1
        e:
            ndtb3qsm0v64ref808o3211rbipok8uc:
                email: 1094028578@qq.com
                executable: C:\Users\BaiYang\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 1015609bc843537f3c73cc1f74ef491ff75d133d
                    remote: git@10.1.30.16:JebGong/cbond_on.git
                host: gongweichen-pc
                os: Windows-10-10.0.26200-SP0
                program: <python with no main file>
                python: CPython 3.11.9
                root: C:\Users\BaiYang\CBOND_ON\cbond_on\rust\factor_engine
                startedAt: "2026-04-07T06:18:13.456955Z"
                writerId: ndtb3qsm0v64ref808o3211rbipok8uc
        m: []
        python_version: 3.11.9
        t:
            "3":
                - 2
            "4": 3.11.9
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
