from __future__ import annotations

from importlib import import_module
from typing import Final


# This ordered table is the explicit default batch-operator profile. Keeping it
# opt-in prevents a generic package import from widening research or live
# execution scope.
_DEFAULT_OPERATOR_IMPORTS: Final[tuple[tuple[str, str], ...]] = (
    ("cbond_on.domain.factors.operators.aacb", "AacbFactor"),
    ("cbond_on.domain.factors.operators.volen", "VolenFactor"),
    ("cbond_on.domain.factors.operators.amount_sum", "AmountSumFactor"),
    ("cbond_on.domain.factors.operators.depth_imbalance", "DepthImbalanceFactor"),
    ("cbond_on.domain.factors.operators.midprice_move", "MidpriceMoveFactor"),
    ("cbond_on.domain.factors.operators.mom_slope", "MomentumSlopeFactor"),
    ("cbond_on.domain.factors.operators.price_position", "PricePositionFactor"),
    ("cbond_on.domain.factors.operators.range_ratio", "RangeRatioFactor"),
    ("cbond_on.domain.factors.operators.ret_open_to_time", "ReturnOpenToTimeFactor"),
    ("cbond_on.domain.factors.operators.ret_window", "ReturnWindowFactor"),
    ("cbond_on.domain.factors.operators.spread", "SpreadFactor"),
    ("cbond_on.domain.factors.operators.turnover_rate", "TurnoverRateFactor"),
    ("cbond_on.domain.factors.operators.volatility", "VolatilityFactor"),
    ("cbond_on.domain.factors.operators.volume_imbalance", "VolumeImbalanceFactor"),
    ("cbond_on.domain.factors.operators.volume_sum", "VolumeSumFactor"),
    ("cbond_on.domain.factors.operators.vwap", "VwapFactor"),
    ("cbond_on.domain.factors.operators.amihud_illiq", "AmihudIlliqFactor"),
    ("cbond_on.domain.factors.operators.microprice_bias", "MicropriceBiasFactor"),
    ("cbond_on.domain.factors.operators.depth_slope", "DepthSlopeFactor"),
    ("cbond_on.domain.factors.operators.return_skew", "ReturnSkewFactor"),
    ("cbond_on.domain.factors.operators.vwap_gap", "VwapGapFactor"),
    ("cbond_on.domain.factors.operators.order_flow_imbalance_v1", "OrderFlowImbalanceV1Factor"),
    ("cbond_on.domain.factors.operators.depth_weighted_imbalance_v1", "DepthWeightedImbalanceV1Factor"),
    ("cbond_on.domain.factors.operators.intraday_momentum_v1", "IntradayMomentumV1Factor"),
    ("cbond_on.domain.factors.operators.volatility_scaled_return_v1", "VolatilityScaledReturnV1Factor"),
    ("cbond_on.domain.factors.operators.volume_price_trend_v1", "VolumePriceTrendV1Factor"),
    ("cbond_on.domain.factors.operators.trade_intensity_v1", "TradeIntensityV1Factor"),
    ("cbond_on.domain.factors.operators.price_level_position_v1", "PriceLevelPositionV1Factor"),
    ("cbond_on.domain.factors.operators.bid_ask_spread_v1", "BidAskSpreadV1Factor"),
    ("cbond_on.domain.factors.operators.stock_bond_momentum_gap_v1", "StockBondMomentumGapV1Factor"),
    ("cbond_on.domain.factors.operators.premium_momentum_proxy_v1", "PremiumMomentumProxyV1Factor"),
    ("cbond_on.domain.factors.operators.alpha001_signed_power_v1", "Alpha001SignedPowerV1Factor"),
    ("cbond_on.domain.factors.operators.alpha002_corr_volume_return_v1", "Alpha002CorrVolumeReturnV1Factor"),
    ("cbond_on.domain.factors.operators.alpha003_corr_open_volume_v1", "Alpha003CorrOpenVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha004_ts_rank_low_v1", "Alpha004TsRankLowV1Factor"),
    ("cbond_on.domain.factors.operators.alpha005_vwap_gap_v1", "Alpha005VwapGapV1Factor"),
    ("cbond_on.domain.factors.operators.alpha006_corr_open_volume_neg_v1", "Alpha006CorrOpenVolumeNegV1Factor"),
    ("cbond_on.domain.factors.operators.alpha007_volume_breakout_v1", "Alpha007VolumeBreakoutV1Factor"),
    ("cbond_on.domain.factors.operators.alpha008_open_return_momentum_v1", "Alpha008OpenReturnMomentumV1Factor"),
    ("cbond_on.domain.factors.operators.alpha009_close_change_filter_v1", "Alpha009CloseChangeFilterV1Factor"),
    ("cbond_on.domain.factors.operators.alpha010_close_change_rank_v1", "Alpha010CloseChangeRankV1Factor"),
    ("cbond_on.domain.factors.operators.alpha011_vwap_close_volume_v1", "Alpha011VwapCloseVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha012_volume_close_reversal_v1", "Alpha012VolumeCloseReversalV1Factor"),
    ("cbond_on.domain.factors.operators.alpha013_cov_close_volume_v1", "Alpha013CovCloseVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha014_return_open_volume_v1", "Alpha014ReturnOpenVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha015_high_volume_corr_v1", "Alpha015HighVolumeCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha016_cov_high_volume_v1", "Alpha016CovHighVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha017_close_rank_volume_v1", "Alpha017CloseRankVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha018_close_open_vol_v1", "Alpha018CloseOpenVolV1Factor"),
    ("cbond_on.domain.factors.operators.alpha019_close_momentum_sign_v1", "Alpha019CloseMomentumSignV1Factor"),
    ("cbond_on.domain.factors.operators.alpha020_open_delay_range_v1", "Alpha020OpenDelayRangeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha021_close_volatility_breakout_v1", "Alpha021CloseVolatilityBreakoutV1Factor"),
    ("cbond_on.domain.factors.operators.alpha022_high_volume_corr_change_v1", "Alpha022HighVolumeCorrChangeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha023_high_momentum_v1", "Alpha023HighMomentumV1Factor"),
    ("cbond_on.domain.factors.operators.alpha024_close_trend_filter_v1", "Alpha024CloseTrendFilterV1Factor"),
    ("cbond_on.domain.factors.operators.alpha025_return_volume_vwap_range_v1", "Alpha025ReturnVolumeVwapRangeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha026_volume_high_rank_corr_v1", "Alpha026VolumeHighRankCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha027_volume_vwap_corr_signal_v1", "Alpha027VolumeVwapCorrSignalV1Factor"),
    ("cbond_on.domain.factors.operators.alpha028_adv_low_close_signal_v1", "Alpha028AdvLowCloseSignalV1Factor"),
    ("cbond_on.domain.factors.operators.alpha029_complex_rank_signal_v1", "Alpha029ComplexRankSignalV1Factor"),
    ("cbond_on.domain.factors.operators.alpha030_close_sign_volume_v1", "Alpha030CloseSignVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha031_close_decay_momentum_v1", "Alpha031CloseDecayMomentumV1Factor"),
    ("cbond_on.domain.factors.operators.alpha032_vwap_close_mean_reversion_v1", "Alpha032VwapCloseMeanReversionV1Factor"),
    ("cbond_on.domain.factors.operators.alpha033_open_close_ratio_v1", "Alpha033OpenCloseRatioV1Factor"),
    ("cbond_on.domain.factors.operators.alpha034_return_volatility_rank_v1", "Alpha034ReturnVolatilityRankV1Factor"),
    ("cbond_on.domain.factors.operators.alpha035_volume_price_momentum_v1", "Alpha035VolumePriceMomentumV1Factor"),
    ("cbond_on.domain.factors.operators.alpha036_complex_correlation_signal_v1", "Alpha036ComplexCorrelationSignalV1Factor"),
    ("cbond_on.domain.factors.operators.alpha037_open_close_correlation_v1", "Alpha037OpenCloseCorrelationV1Factor"),
    ("cbond_on.domain.factors.operators.alpha038_close_rank_ratio_v1", "Alpha038CloseRankRatioV1Factor"),
    ("cbond_on.domain.factors.operators.alpha039_volume_decay_momentum_v1", "Alpha039VolumeDecayMomentumV1Factor"),
    ("cbond_on.domain.factors.operators.alpha040_high_volatility_corr_v1", "Alpha040HighVolatilityCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha041_geometric_mean_vwap_v1", "Alpha041GeometricMeanVwapV1Factor"),
    ("cbond_on.domain.factors.operators.alpha042_vwap_close_rank_ratio_v1", "Alpha042VwapCloseRankRatioV1Factor"),
    ("cbond_on.domain.factors.operators.alpha043_volume_delay_momentum_v1", "Alpha043VolumeDelayMomentumV1Factor"),
    ("cbond_on.domain.factors.operators.alpha044_high_volume_rank_corr_v1", "Alpha044HighVolumeRankCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha045_close_sum_corr_v1", "Alpha045CloseSumCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha046_close_delay_trend_v1", "Alpha046CloseDelayTrendV1Factor"),
    ("cbond_on.domain.factors.operators.alpha047_inverse_close_volume_v1", "Alpha047InverseCloseVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha049_close_delay_threshold_v1", "Alpha049CloseDelayThresholdV1Factor"),
    ("cbond_on.domain.factors.operators.alpha050_volume_vwap_corr_max_v1", "Alpha050VolumeVwapCorrMaxV1Factor"),
    ("cbond_on.domain.factors.operators.alpha051_close_delay_threshold_v2_v1", "Alpha051CloseDelayThresholdV2V1Factor"),
    ("cbond_on.domain.factors.operators.alpha052_low_momentum_volume_v1", "Alpha052LowMomentumVolumeV1Factor"),
    ("cbond_on.domain.factors.operators.alpha053_price_position_delta_v1", "Alpha053PricePositionDeltaV1Factor"),
    ("cbond_on.domain.factors.operators.alpha054_price_power_ratio_v1", "Alpha054PricePowerRatioV1Factor"),
    ("cbond_on.domain.factors.operators.alpha055_close_range_volume_corr_v1", "Alpha055CloseRangeVolumeCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha057_close_vwap_decay_v1", "Alpha057CloseVwapDecayV1Factor"),
    ("cbond_on.domain.factors.operators.alpha060_price_range_volume_scale_v1", "Alpha060PriceRangeVolumeScaleV1Factor"),
    ("cbond_on.domain.factors.operators.alpha062_vwap_open_rank_compare_v1", "Alpha062VwapOpenRankCompareV1Factor"),
    ("cbond_on.domain.factors.operators.alpha065_open_vwap_min_signal_v1", "Alpha065OpenVwapMinSignalV1Factor"),
    ("cbond_on.domain.factors.operators.alpha066_vwap_low_decay_v1", "Alpha066VwapLowDecayV1Factor"),
    ("cbond_on.domain.factors.operators.alpha068_high_adv_rank_signal_v1", "Alpha068HighAdvRankSignalV1Factor"),
    ("cbond_on.domain.factors.operators.alpha072_vwap_volume_decay_ratio_v1", "Alpha072VwapVolumeDecayRatioV1Factor"),
    ("cbond_on.domain.factors.operators.alpha073_vwap_open_decay_max_v1", "Alpha073VwapOpenDecayMaxV1Factor"),
    ("cbond_on.domain.factors.operators.alpha074_close_adv_rank_corr_v1", "Alpha074CloseAdvRankCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha075_vwap_volume_low_adv_corr_v1", "Alpha075VwapVolumeLowAdvCorrV1Factor"),
    ("cbond_on.domain.factors.operators.alpha077_mid_price_adv_decay_min_v1", "Alpha077MidPriceAdvDecayMinV1Factor"),
    ("cbond_on.domain.factors.operators.alpha078_low_vwap_adv_corr_v1", "Alpha078LowVwapAdvCorrV1Factor"),
    ("cbond_on.domain.factors.operators.daily_overnight_return_mean_v1", "DailyOvernightReturnMeanV1Factor"),
    ("cbond_on.domain.factors.operators.daily_sharpe_mean_v1", "DailySharpeMeanV1Factor"),
    ("cbond_on.domain.factors.operators.t1430_amount_accel_30m_v1", "T1430AmountAccel30mV1"),
    ("cbond_on.domain.factors.operators.t1430_depth_concentration_v1", "T1430DepthConcentrationV1"),
    ("cbond_on.domain.factors.operators.t1430_depth_imbalance_change_v1", "T1430DepthImbalanceChangeV1"),
    ("cbond_on.domain.factors.operators.t1430_last_return_30m_v1", "T1430LastReturn30mV1"),
    ("cbond_on.domain.factors.operators.t1430_microprice_last_gap_v1", "T1430MicropriceLastGapV1"),
    ("cbond_on.domain.factors.operators.t1430_mid_return_30m_v1", "T1430MidReturn30mV1"),
    ("cbond_on.domain.factors.operators.t1430_price_range_30m_v1", "T1430PriceRange30mV1"),
    ("cbond_on.domain.factors.operators.t1430_spread_change_30m_v1", "T1430SpreadChange30mV1"),
    ("cbond_on.domain.factors.operators.t1430_spread_mean_guarded_30m_v1", "T1430SpreadMeanGuarded30mV1"),
    ("cbond_on.domain.factors.operators.t1430_window_vwap_last_gap_v1", "T1430WindowVwapLastGapV1"),
    ("cbond_on.domain.factors.operators.t1430_cumulative_volume_ratio_v1", "T1430CumulativeVolumeRatioV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_gini_coefficient_v1", "T1430VolumeGiniCoefficientV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_autocorrelation_v1", "T1430VolumeAutocorrelationV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_momentum_v1", "T1430VolumeMomentumV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_std_dev_v1", "T1430VolumeStdDevV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_skewness_v1", "T1430VolumeSkewnessV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_kurtosis_v1", "T1430VolumeKurtosisV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_count_v1", "T1430VolumeCountV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_cumsum_v1", "T1430VolumeCumsumV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_mean_v1", "T1430VolumeMeanV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_max_v1", "T1430VolumeMaxV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_min_v1", "T1430VolumeMinV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_count_v2", "T1430VolumeCountV2"),
    ("cbond_on.domain.factors.operators.t1430_volume_acceleration_v1", "T1430VolumeAccelerationV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_concentration_hhi_v1", "T1430VolumeConcentrationHhiV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_cv_v1", "T1430VolumeCvV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_entropy_v1", "T1430VolumeEntropyV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_gini_simple_v1", "T1430VolumeGiniSimpleV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_concentration_gini_v1", "T1430VolumeConcentrationGiniV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_weighted_avg_size_v1", "T1430VolumeWeightedAvgSizeV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_hhi_v1", "T1430VolumeHhiV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_hhi_v2", "T1430VolumeHhiV2"),
    ("cbond_on.domain.factors.operators.t1430_volume_entropy_v2", "T1430VolumeEntropyV2"),
    ("cbond_on.domain.factors.operators.t1430_volume_cumsum_slope_v1", "T1430VolumeCumsumSlopeV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_recent_share_v1", "T1430VolumeRecentShareV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_weighted_time_center_v1", "T1430VolumeWeightedTimeCenterV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_moment_v1", "T1430VolumeMomentV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_sum_v1", "T1430VolumeSumV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_max_tick_v1", "T1430VolumeMaxTickV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_range_v1", "T1430VolumeRangeV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_count_v3", "T1430VolumeCountV3"),
    ("cbond_on.domain.factors.operators.t1430_volume_mean_v2", "T1430VolumeMeanV2"),
    ("cbond_on.domain.factors.operators.t1430_volume_std_dev_v2", "T1430VolumeStdDevV2"),
    ("cbond_on.domain.factors.operators.t1430_volume_max_v2", "T1430VolumeMaxV2"),
    ("cbond_on.domain.factors.operators.t1430_volume_min_v2", "T1430VolumeMinV2"),
    ("cbond_on.domain.factors.operators.microprice_dev_liquidity_v1", "MicropriceDevLiquidityV1"),
    ("cbond_on.domain.factors.operators.ob_pressure_spread_recovery_v1", "ObPressureSpreadRecoveryV1"),
    ("cbond_on.domain.factors.operators.ob_pressure_spread_v1", "ObPressureSpreadV1"),
    ("cbond_on.domain.factors.operators.microprice_deviation_v1", "MicropriceDeviationV1"),
    ("cbond_on.domain.factors.operators.microprice_deviation_liq_cond_v1", "MicropriceDeviationLiqCondV1"),
    ("cbond_on.domain.factors.operators.spread_depth_pressure_v1", "SpreadDepthPressureV1"),
    ("cbond_on.domain.factors.operators.microprice_deviation_liq_v1", "MicropriceDeviationLiqV1"),
    ("cbond_on.domain.factors.operators.vwap_deviation_liquidity_cond_v1", "VwapDeviationLiquidityCondV1"),
    ("cbond_on.domain.factors.operators.tail_volume_absorption_v1", "TailVolumeAbsorptionV1"),
    ("cbond_on.domain.factors.operators.ob_pressure_spread_persistence_v1", "ObPressureSpreadPersistenceV1"),
    ("cbond_on.domain.factors.operators.t1430_pv_interaction_v1", "T1430PvInteractionV1"),
    ("cbond_on.domain.factors.operators.t1430_range_vol_norm_v1", "T1430RangeVolNormV1"),
    ("cbond_on.domain.factors.operators.t1430_tail_pressure_v1", "T1430TailPressureV1"),
    ("cbond_on.domain.factors.operators.t1430_range_volume_v1", "T1430RangeVolumeV1"),
    ("cbond_on.domain.factors.operators.t1430_amount_intensity_v1", "T1430AmountIntensityV1"),
    ("cbond_on.domain.factors.operators.t1430_close_position_v1", "T1430ClosePositionV1"),
    ("cbond_on.domain.factors.operators.t1430_pv_ratio_v1", "T1430PvRatioV1"),
    ("cbond_on.domain.factors.operators.t1430_range_volume_norm_v1", "T1430RangeVolumeNormV1"),
    ("cbond_on.domain.factors.operators.t1430_range_norm_volume_v1", "T1430RangeNormVolumeV1"),
    ("cbond_on.domain.factors.operators.t1430_amount_vol_ratio_v1", "T1430AmountVolRatioV1"),
    ("cbond_on.domain.factors.operators.t1430_close_range_position_v1", "T1430CloseRangePositionV1"),
    ("cbond_on.domain.factors.operators.t1430_volatility_turnover_v1", "T1430VolatilityTurnoverV1"),
    ("cbond_on.domain.factors.operators.t1430_vwap_deviation_v1", "T1430VwapDeviationV1"),
    ("cbond_on.domain.factors.operators.t1430_vol_turnover_ratio_v1", "T1430VolTurnoverRatioV1"),
    ("cbond_on.domain.factors.operators.t1430_spread_liquidity_ratio_v1", "T1430SpreadLiquidityRatioV1"),
    ("cbond_on.domain.factors.operators.t1430_microprice_mid_deviation_v1", "T1430MicropriceMidDeviationV1"),
    ("cbond_on.domain.factors.operators.t1430_orderflow_imbalance_v1", "T1430OrderflowImbalanceV1"),
    ("cbond_on.domain.factors.operators.t1430_depth_weighted_mid_v1", "T1430DepthWeightedMidV1"),
    ("cbond_on.domain.factors.operators.t1430_bid_ask_imbalance_v1", "T1430BidAskImbalanceV1"),
    ("cbond_on.domain.factors.operators.t1430_microprice_midpoint_dev_v1", "T1430MicropriceMidpointDevV1"),
    ("cbond_on.domain.factors.operators.t1430_order_flow_toxicity_v1", "T1430OrderFlowToxicityV1"),
    ("cbond_on.domain.factors.operators.t1430_bid_ask_spread_v1", "T1430BidAskSpreadV1"),
    ("cbond_on.domain.factors.operators.t1430_order_imbalance_v1", "T1430OrderImbalanceV1"),
    ("cbond_on.domain.factors.operators.t1430_micro_price_deviation_v1", "T1430MicroPriceDeviationV1"),
    ("cbond_on.domain.factors.operators.t1430_relative_strength_v1", "T1430RelativeStrengthV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_weighted_price_deviation_v1", "T1430VolumeWeightedPriceDeviationV1"),
    ("cbond_on.domain.factors.operators.t1430_mid_price_return_v1", "T1430MidPriceReturnV1"),
    ("cbond_on.domain.factors.operators.t1430_spread_width_norm_v1", "T1430SpreadWidthNormV1"),
    ("cbond_on.domain.factors.operators.t1430_microprice_mid_spread_v1", "T1430MicropriceMidSpreadV1"),
    ("cbond_on.domain.factors.operators.t1430_order_flow_imbalance_v1", "T1430OrderFlowImbalanceV1"),
    ("cbond_on.domain.factors.operators.t1430_relative_bid_ask_strength_v1", "T1430RelativeBidAskStrengthV1"),
    ("cbond_on.domain.factors.operators.t1430_liq_adj_spread_v1", "T1430LiqAdjSpreadV1"),
    ("cbond_on.domain.factors.operators.t1430_microprice_imbalance_v1", "T1430MicropriceImbalanceV1"),
    ("cbond_on.domain.factors.operators.t1430_volume_weighted_mid_v1", "T1430VolumeWeightedMidV1"),
    ("cbond_on.domain.factors.operators.t1430_microprice_liquidity_v1", "T1430MicropriceLiquidityV1"),
    ("cbond_on.domain.factors.operators.t1430_ob_imbalance_flow_v1", "T1430ObImbalanceFlowV1"),
    ("cbond_on.domain.factors.operators.t1430_spread_volatility_ratio_v1", "T1430SpreadVolatilityRatioV1"),
    ("cbond_on.domain.factors.operators.t1430_relative_strength_vwap_v1", "T1430RelativeStrengthVwapV1"),
    ("cbond_on.domain.factors.operators.t1430_depth_pressure_return_v1", "T1430DepthPressureReturnV1"),
    ("cbond_on.domain.factors.operators.t1430_price_range_depth_ratio_v1", "T1430PriceRangeDepthRatioV1"),
)

DEFAULT_OPERATOR_COUNT: Final[int] = len(_DEFAULT_OPERATOR_IMPORTS)


def load_default_operators() -> tuple[str, ...]:
    """Register the default batch-operator profile explicitly.

    This is deliberately the only place that imports all former default
    definitions. It is idempotent under normal Python module caching and
    exposes the class attributes on the canonical operator package for
    compatibility with the existing batch path.
    """

    operators_module = import_module("cbond_on.domain.factors.operators")
    for module_path, class_name in _DEFAULT_OPERATOR_IMPORTS:
        operator_module = import_module(module_path)
        setattr(operators_module, class_name, getattr(operator_module, class_name))
    return tuple(module_path for module_path, _ in _DEFAULT_OPERATOR_IMPORTS)


__all__ = [
    "DEFAULT_OPERATOR_COUNT",
    "load_default_operators",
]
